spring:
  application:
    name: lbgateway2
#
#  cloud:
#   gateway:
#      discovery:
#        locator: 
#         enabled: true
#      routes:
#          - id: lbservice-route
#            uri: lb://LBSERVICE
#            predicates:
#              - Path=/test/**     
#Commented because we are creatimg a springcloudconfinguration.java ...if delete that ..remove the comments too
server:
  port: 9999
 
#management:
#  endpoint:
#    gateway:
#      enabled: true 

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  


  